exec_always sh -c 'pkill waybar; sleep 0.5; waybar &'
exec_always sh -c 'pkill mako; sleep 0.5; mako &'
exec swayidle -w \
    timeout 900 'swaylock' \
    before-sleep 'swaylock'
exec systemctl --user import-environment XDG_DATA_DIRS
exec /usr/lib/xdg-desktop-portal-wlr &
exec /usr/lib/xdg-desktop-portal &
exec_always pkill swaybg; swaybg -i ~/Pictures/wallpaper.png -m fill &

# Scratchpad apps — se lanzan una vez y van al scratchpad automáticamente
exec otpclient
