# ============================================
# VENTANAS FLOTANTES
# ============================================

# OTPClient — scratchpad
for_window [app_id="com.github.paolostivanin.OTPClient"] {
    floating enable
    resize set 380 520
    move position center
    move to scratchpad
}
