# Fuente
font pango:monospace 10

# Bordes
default_border pixel 1
default_floating_border pixel 1
hide_edge_borders smart
gaps inner 4
gaps outer 0

# SwayFX effects
blur enable
blur_passes 2
blur_radius 5
corner_radius 6
shadows enable
shadow_blur_radius 10
shadow_color #00000066

# Colores
# class                 border  bg      text    indicator child_border
client.focused          #444444 #222222 #ffffff #444444   #444444
client.focused_inactive #222222 #1a1a1a #888888 #222222   #222222
client.unfocused        #1a1a1a #111111 #555555 #1a1a1a   #1a1a1a
client.urgent           #cc3333 #cc3333 #ffffff #cc3333   #cc3333
